# FROM node:17-alpine as build
# WORKDIR /tosidrop
# COPY . .
# RUN npm install
# RUN npm run build

FROM nginx:stable-alpine
COPY ./build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]